### ISSUE TITLE
Adopt a code of conduct for the meetup

### ISSUE THREAD

**Issue by nathenharvey** [devopsdc/devopsdc#12]
A proposed code of conduct has been added to this repo - https://github.com/devopsdc/devopsdc/blob/master/code_of_conduct.md

Please comment here and/or submit PRs against that code of conduct.

**Comment by mcornick** [comment]
:+1: this is in line with what other similar groups are doing, and reusing existing text rather than writing our own is a good idea.

**Comment by nathenharvey** [comment]
FWIW, I stole this directly from https://www.chef.io/blog/chefconfcodeofconduct/ which was derived from a couple of other sources as listed in the copy.

**Comment by adamleff** [comment]
:+1: as written.

**Comment by nathenharvey** [comment]
This has been officially adopted as our code of conduct.  
- [Announced on the mailing list](http://www.meetup.com/DevOpsDC/messages/boards/thread/49204741)
- [Available on the meetup site](http://www.meetup.com/DevOpsDC/pages/Code_of_Conduct/)

This should be mentioned at each meeting moving forward.
