### ISSUE TITLE
DevOps and Change Management: Don't Leave Your Users Behind

### ISSUE THREAD

**Issue by jwasiolek** [devopsdc/devopsdc#57]
## Name

Janusz Wasiolek
jwasiolek@gmail.com or Janusz.Wasiolek@hq.dhs.gov
https://www.linkedin.com/in/janusz-wasiolek-cem-1b772257/

## Blurb

Your software can update a hundred times per day. Your users can't. Learn how to apply change management principles to your DevOps processes and make sure your users aren't left behind.

## Other

#changemanagement
#usersfirst

**Comment by pburkholder** [comment]
@jwasiolek Are you still up for doing this? I just met with the co-organizers and realized we'd had this in limbo. What's your availability for the next few months on the 2nd Tuesday of the month

Oct 8
Nov 12
Dec 10
Jan 14 ?

**Comment by jwasiolek** [comment]
Hi Peter, any of those should work. Thanks!
