### ISSUE TITLE
Speaker Proposal

### ISSUE THREAD

**Issue by mcgonagle** [devopsdc/devopsdc#61]
## Speaker

Thomas A. McGonagle
GH mcgonagle
Twitter @mcgonagle

## Blurb

Teamwork is the Engine of a High Performing Organization and Empathy is the Gas.

## Other

Spinnaker helps with teamwork as it maps well to the 10 teamwork processes, which are (from  https://en.wikipedia.org/wiki/Teamwork) :
Mission analysis
Goal specification
Strategy formulation
Monitoring progress toward goals
Systems thinking
Team monitoring and backup behavior
Coordination
Conflict management
Motivation and confidence building
Affect management

**Comment by pburkholder** [comment]
Thanks for your proposal. I missed it while on vacation. Is this a talk you've done before? Are you generally available on 2nd tuesdays of the month?

Also, do you work for/on Spinnaker or just a satisfied adopter?

Had I been aware I would've tried to pair this with our Gitlab talk this week. I hope you can make it on Thursday and provide some compare/contrast with your experience.

Cheers, Peter
