### ISSUE TITLE
Speaker Proposal: Building A Compliance Aware Cloud with Continuous Compliance Monitoring

### ISSUE THREAD

**Issue by nemetzj** [devopsdc/devopsdc#64]
## Speaker

Jacob Nemetz, CEO
[Dash Solutions](https://www.dashsdk.com)
jacob@dashsdk.com
[https://www.linkedin.com/in/nemetz/](https://www.linkedin.com/in/nemetz/)

Jacob Nemetz is the CEO of Dash Solutions, a company that provides solutions for configuring, monitoring, and maintaining regulatory compliance in Amazon Web Services (AWS). Dash provides organizations with a process for creating custom administrative policies, technical controls, and compliance monitoring to maintain compliance in the cloud. Previously Nemetz founded and developed HIPAA compliant applications for patient engagement company Intraclinics and has developed security programs for a number of organizations.

## Blurb
As regulated industries such as healthcare and finance continue to transition into the cloud, the need for consistent security configuration and compliance management becomes increasingly necessary. A single “mis-configured” cloud resource can result in a data breach, as seen with the latest breach at Capital One. Automating security tasks, mapping security controls to regulatory standards, and implementing continuous compliance monitoring are essential for ensuring compliance in the cloud. In this session we will explore how DevOps teams can automate compliance functions and security configuration in the cloud.

Key Takeaways:
- The Cloud Shared Responsibility Model, and your security responsibilities as a cloud customer.
- Defining security policies that fit with your cloud environment and fit into regulatory frameworks.
- Building cloud security controls around regulatory frameworks (HIPAA, NIST, ISO, SOC).
- Steps for automating cloud security configuration and resource management with continuous compliance monitoring.

**Comment by pburkholder** [comment]
Thanks so much for the submission. This looks pretty interesting.  Is this a talk  that you've done before (if so, that's okay -- any recordings?) How much of it is specific Dash products? 

Cheers, Peter

**Comment by nemetzj** [comment]
Hi Peter,

This is a relatively new talk given to some smaller local groups, so I do not have any recordings. The talk is not specific to Dash products, with Dash only being referenced for an example. 

Otherwise the presentation includes planning, executing, and automating compliance processes, including some example processes/solutions using AWS cloud services and other point solutions (auditing, intrusion detection, firewall..).

Let me know your thoughts and next steps. 

Best,
Jacob

**Comment by pburkholder** [comment]
How about 11/12 then?

**Comment by nemetzj** [comment]
11/12 works for me. How much time do you typically allocate for each talk?
