### ISSUE TITLE
May, 2015 - Training Day?

### ISSUE THREAD

**Issue by nathenharvey** [devopsdc/devopsdc#7]
We discussed running a free full-day training session in advance of the May meeting.

@pburkholder, we should continue those discussions and come up with some details that we can announce by the April 14th meeting at the latest.

**Comment by pburkholder** [comment]
You can assign this to me, or give me permissions to assign myself. Thanks.

**Comment by nathenharvey** [comment]
@pburkholder you should have full access to this repo now.

**Comment by pburkholder** [comment]
Odd, I don't have any new access.

On Wed, Mar 11, 2015 at 3:04 PM, Nathen Harvey notifications@github.com
wrote:

> @pburkholder https://github.com/pburkholder you should have full access
> to this repo now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/devopsdc/devopsdc/issues/7#issuecomment-78347295.

## 

_Peter Burkholder_ — Customer Success Engineer

Unavailability: Travel March 2-3; Vacation March 16-20; ChefConf March
30-April 3

301-204-5767 – pburkholder@chef.io – *my: *Linkedin
http://www.linkedin.com/in/pburkholder  Twitter
http://www.twitter.com/pburkholder  Cal
https://www.google.com/calendar/embed?src=pburkholder%40chef.io&mode=WEEK
endar

_CHEF_

CHEF.IO http://www.chef.io/

TM

_chef.io_ http://www.chef.io/   Blog http://www.chef.io/blog/   Facebook
https://www.facebook.com/getchefdotcom   Twitter
https://twitter.com/chef   Youtube https://www.youtube.com/getchef
