### ISSUE TITLE
Code and Coffee?

### ISSUE THREAD

**Issue by nathenharvey** [devopsdc/devopsdc#9]
let's schedule a code and coffee session that runs soon with a loose agenda

maybe one that's pre-working hours and one that's post-working hours so we can read demand and timing preferences.

**Comment by chrispernicano** [comment]
There's a group that does code & coffee at our office in Fairfax on one Saturday morning each month, if Saturday is something people would be interested in, rather than trying to battle traffic during the week. I also imagine we would be open to hosting (weekday evening or weekend)
